const SESSION_KEY = 'aia-auto-ip-session';
const state = { matched: false, profile: {}, currentQuestion: 0, done: false, version: 1, pendingUpdate: null, multiSelection: new Set(), hasHistory: false, proposals: [], generating: false, autoGenerated: false, activeTool: 'ip', requestedTool: 'ip' };
const planningState = { context: {}, currentQuestion: 0, done: false, started: false, hasHistory: false, messages: [], plans: [], version: 1, generating: false };
const COMPLIANCE_TIPS = {
  allowed: [
    { emoji: '✅', title: '真实信息', text: '可表达真实的个人经历、城市、专业服务方向与已获得的荣誉。' },
    { emoji: '✅', title: '合规称谓', text: '小红书可使用“代理人”“养老规划师”等合规称谓。' },
    { emoji: '✅', title: '内容场景', text: '视频和图文笔记（非简介）可按公司规则宣传友邦。' },
  ],
  avoid: [
    { emoji: '⛔', title: '联系方式与导流', text: '简介不得写微信号、手机号、邮箱、QQ、微博、二维码或其他平台账号。' },
    { emoji: '⛔', title: '诱导行为', text: '不要写“关注送福利”“私信领资料”等引导关注或利益诱导。' },
    { emoji: '⛔', title: '小红书敏感词', text: '小红书简介避免保险、金融、理财、贷款、股票、基金、医疗、护理、教育、玄学。' },
    { emoji: '⛔', title: '品牌与编号', text: '小红书简介不得出现友邦、AIA，也不要写执业证编号。' },
    { emoji: '⛔', title: '夸大承诺', text: '避免“最好、第一、保证、稳赚、无风险”等绝对化或不实表述。' },
    { emoji: '⛔', title: '医疗引流', text: '不要引导问诊、讨论疾病，或引导到站外学习医疗知识。' },
    { emoji: '⛔', title: '招募与招商', text: '不要以个人名义招募、招聘营销员，或进行招商加盟、诱导创业投资。' },
    { emoji: '⛔', title: '账号识别号', text: '微信号、小红书号、抖音号不得包含友邦、AIA 及其拼音或缩写。' },
  ],
};

const questions = [
  { key: 'city', label: '所在城市', ask: '请补充你主要服务的城市。', chips: ['成都', '上海', '北京', '广州'] },
  { key: 'customerGroups', label: '服务人群', ask: '你最希望服务哪些人群？可多选；也可以自行输入补充。', chips: ['企业主', '职场白领', '宝爸宝妈', '都市银发', '自由职业者', '新市民'], multiple: true },
  { key: 'customerAges', label: '客户年龄段', ask: '你的目标客户主要处在哪些年龄段？可多选。', chips: ['25–35 岁', '35–45 岁', '45–55 岁', '55 岁以上'], multiple: true },
  { key: 'insuranceYears', label: '保险从业时间', ask: '你从事保险相关工作多少年？请只输入具体数字，例如 9。', chips: [], inputMode: 'numeric', suffix: '年' },
  { key: 'strengths', label: '你的优势', ask: '以下哪些最能代表你的优势？可多选，也可以自行输入补充。', chips: ['专业靠谱', '善于沟通', '有温度', '行动力强', '耐心倾听', '资源整合', '善于规划'], multiple: true },
  { key: 'honors', label: '荣誉', ask: '请选择你获得的荣誉，可多选；如有其他荣誉，也可以自行输入。', chips: ['MDRT', 'COT', 'TOT', '五星会员'], multiple: true },
  { key: 'education', label: '学历', ask: '你的最高学历是什么？这项只用于判断是否适合在昵称或简介中突出。', chips: ['本科', '硕士', '博士', '不希望填写'] },
  { key: 'schoolTier', label: '学校背景', ask: '如愿意，可补充最高学校背景，例如 985、211、QS 前 100。', chips: ['985', '211', 'QS 前 100', '跳过'] },
  { key: 'overseas', label: '留学背景', ask: '是否有留学背景？', chips: ['有', '没有', '不希望填写'] },
  { key: 'contentTone', label: '希望呈现的气质', ask: '你希望账号给人的第一感觉是什么？', chips: ['专业理性', '温暖陪伴', '干练直接', '生活化真诚'] },
  { key: 'department', label: '营销服务部', ask: '最后，请填写你的营销服务部名称，用于视频号和抖音的合规文案。', chips: [] },
];

const labels = {
  name: '姓名', agentId: '营销员编号', selfIntro: '自我介绍', purpose: '做自媒体目的', city: '所在城市',
  customerGroups: '服务人群', customerAges: '客户年龄段', insuranceYears: '保险从业时间', strengths: '你的优势', honors: '荣誉',
  education: '学历', schoolTier: '学校背景', overseas: '留学背景', contentTone: '希望呈现的气质',
  department: '营销服务部', generationNotes: '生成偏好',
};

const planningQuestions = [
  { key: 'primaryGoal', ask: '亲，这个账号接下来最想解决什么？先确定主目标，后面的合集才不会东一块、西一块。', chips: ['拓客为主', '增员为主', '两者兼顾'] },
  { key: 'insuranceFocus', ask: '保险这条主线，你更希望重点讲什么？可以从下面选，也可以直接说你的想法。', chips: ['家庭保障', '教育金规划', '养老规划', '财富保障'] },
  { key: 'secondaryMaterials', ask: '除了保险，你有哪些适合长期分享的真实积累？例如育儿、医疗背景、骑行、职业经历。想到什么就说什么，我来帮你筛选。', chips: ['育儿与升学', '健康生活', '高质量运动', '职业成长'] },
  { key: 'audienceHelp', ask: '你最希望这类人从账号里得到什么帮助？一句话就够，例如“让新手爸妈看懂教育金”。', chips: ['风险保障思路', '家庭教育规划', '养老准备常识', '职业转型参考'] },
];

const $ = (id) => document.getElementById(id);
const messages = $('messages');

const toolDetails = {
  planning: {
    icon: '🗂️', eyebrow: '账号内容规划', title: '让账号内容不再像朋友圈',
    description: '以当前 IP 为基础，先筛选“保险 + N”，再为账号确定唯一的“保险 + 1”内容结构。',
    cards: [['保险主线', '确定保障、教育金、养老等适合你的保险内容核心。'], ['泛内容筛选', '从育儿、医疗、运动等候选方向中，只保留最匹配的一项。'], ['作品合集', '按拓客或增员的信任路径，整理合集、选题与优先级。']],
    note: '内容不能太杂、太随意地混发；平台要先读懂你的账号，才知道该把你推给谁。',
  },
  script: {
    icon: '✍️', eyebrow: '脚本改写', title: '把一个好选题，写成像你说的话',
    description: '粘贴已有脚本或从内容规划中选择选题；系统会先判断是否需要带入你的 IP。',
    cards: [['识别场景', '判断内容是否需要体现你的城市、专业方向和个人经历。'], ['多版改写', '保留原意，调整结构、表达方式与手机阅读节奏。'], ['合规核对', '避免未经确认的个人经历、夸大承诺和不合规表达。']],
    note: '脚本方法将以确认后的内部指令文档为准，并与当前 IP 方案协同使用。',
  },
  xhs: {
    icon: '📱', eyebrow: '小红书排版', title: '让内容看起来更像一篇愿意读完的笔记',
    description: '将确认后的文案整理为标题、段落、小标题与表情建议，并提供可直接复制的发布版本。',
    cards: [['阅读节奏', '根据手机屏幕自动控制段落长度与留白。'], ['账号风格', '需要时带入当前 IP 的表达气质和目标人群。'], ['发布前提示', '在复制前核对敏感词、引流和夸大承诺风险。']],
    note: '排版服务于清晰表达，不会为了“好看”添加虚构经历或不合规信息。',
  },
};

function renderToolPlaceholder(tool) {
  const detail = toolDetails[tool];
  if (!detail) return;
  const panel = $('tool-placeholder');
  panel.innerHTML = `<div class="tool-stage-heading"><span class="tool-stage-icon">${detail.icon}</span><div><p class="eyebrow">${detail.eyebrow} · 功能预览</p><h2>${detail.title}</h2><p>${detail.description}</p></div><span class="tool-stage-status">正在设计</span></div><div class="tool-stage-cards">${detail.cards.map(([title, text], index) => `<article><span>0${index + 1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div><div class="tool-stage-context"><strong>将使用当前 IP 上下文</strong><span>${state.profile.name ? `已关联：${state.profile.name} 的资料与 IP 方案` : '登录并建立 IP 档案后，将自动关联个人资料与方案版本'}</span></div><p class="tool-stage-note">📌 ${detail.note}</p>`;
}

function selectTool(tool) {
  state.activeTool = tool;
  document.querySelectorAll('[data-tool]').forEach((button) => button.classList.toggle('active', button.dataset.tool === tool));
  const isIp = tool === 'ip';
  const isPlanning = tool === 'planning';
  $('ip-chat-panel').classList.toggle('hidden', !isIp);
  $('planning-panel').classList.toggle('hidden', !isPlanning);
  $('tool-placeholder').classList.toggle('hidden', isIp || isPlanning);
  $('generate-button').classList.toggle('hidden', !isIp);
  if (!isIp) $('view-proposal').classList.add('hidden');
  else refreshProposalButton();
  if (isPlanning) activatePlanning();
  else if (!isIp) renderToolPlaceholder(tool);
}

function chooseToolBeforeLogin(tool) {
  state.requestedTool = tool;
  document.querySelectorAll('.identity-tool').forEach((button) => button.classList.toggle('active', button.dataset.tool === tool));
}

const planningMessages = () => $('planning-messages');

function addPlanningMessage(text, kind = 'assistant', persist = true) {
  const node = document.createElement('div');
  node.className = `message ${kind}`;
  node.textContent = text;
  planningMessages().appendChild(node);
  planningMessages().scrollTop = planningMessages().scrollHeight;
  if (persist && state.matched) persistPlanningMessage(kind, text);
  return node;
}

async function persistPlanningMessage(role, content) {
  try {
    await fetch('/api/content-plan/message', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agentId: state.profile.agentId, role, content }) });
  } catch (_) { $('planning-save-state').textContent = '暂未保存，请检查网络'; }
}

function setPlanningChips(question) {
  const area = $('planning-quick-replies');
  area.innerHTML = '';
  if (!question) return;
  question.chips.forEach((chip) => {
    const button = document.createElement('button');
    button.textContent = chip;
    button.onclick = () => planningAnswer(chip);
    area.appendChild(button);
  });
}

function planningReadyPrompt() {
  const node = document.createElement('div');
  node.className = 'message assistant';
  const words = document.createElement('div');
  words.textContent = '亲，关键素材已经收到。现在可以按“保险 + N → 保险 + 1”给你做第一版内容规划。';
  const button = document.createElement('button');
  button.className = 'primary confirm-update';
  button.textContent = '生成我的内容规划';
  button.onclick = () => generateContentPlan();
  node.append(words, button); planningMessages().appendChild(node); planningMessages().scrollTop = planningMessages().scrollHeight;
}

function presentPlanningQuestion() {
  const question = planningQuestions[planningState.currentQuestion];
  if (!question) {
    planningState.done = true;
    $('planning-title').textContent = '可以生成你的专属内容规划';
    $('planning-input').placeholder = '也可以直接说“生成内容规划”…';
    setPlanningChips(null); planningReadyPrompt(); return;
  }
  if (planningState.context[question.key]) { planningState.currentQuestion += 1; return presentPlanningQuestion(); }
  $('planning-title').textContent = '通过对话确定你的 1 + 1';
  $('planning-input').placeholder = '输入你的回答…';
  addPlanningMessage(question.ask); setPlanningChips(question);
}

function refreshContentPlanButton() {
  const button = $('view-content-plan');
  if (planningState.plans.length) { button.classList.remove('hidden'); button.textContent = `查看最新方案 · V${planningState.plans[0].version}`; }
  else button.classList.add('hidden');
}

function activatePlanning() {
  if (planningState.started) return;
  planningState.started = true;
  $('planning-save-state').textContent = state.matched ? '内容规划将保存到历史档案' : '本次会话';
  if (planningState.messages.length) {
    planningState.messages.forEach((item) => addPlanningMessage(item.content, item.role, false));
    planningState.done = planningState.plans.length > 0;
  }
  if (planningState.plans.length) {
    planningState.context = { primaryGoal: planningState.plans[0].plan.primaryGoal || '', insuranceFocus: planningState.plans[0].plan.insuranceLine?.title || '' };
    $('planning-title').textContent = '继续聊聊，随时调整方案';
    if (!planningState.messages.length) addPlanningMessage('亲，你已经有一版内容规划了。直接告诉我想调整什么，例如“第二主线更偏育儿”或“合集增加增员内容”，我会生成新版本。');
    refreshContentPlanButton(); return;
  }
  addPlanningMessage(state.profile.name ? `亲，${state.profile.name}，IP 资料会自动带入。我们再补四个和内容方向有关的问题，就能生成你的内容规划。` : '亲，IP 资料会自动带入。我们再补四个和内容方向有关的问题，就能生成你的内容规划。');
  presentPlanningQuestion();
}

function isContentPlanRequest(text) {
  return /(?:生成|出|做|看看).{0,8}(?:内容规划|规划方案|合集)|^(?:帮我|请|现在|直接|可以).{0,10}(?:规划|出方案)/.test(text);
}

async function planningAnswer(value) {
  const content = value.trim(); if (!content) return;
  if (planningState.done) {
    addPlanningMessage(content, 'user');
    if (!planningState.plans.length || isContentPlanRequest(content)) return generateContentPlan();
    return reviseContentPlan(content);
  }
  const question = planningQuestions[planningState.currentQuestion];
  addPlanningMessage(content, 'user'); planningState.context[question.key] = content; planningState.currentQuestion += 1;
  setPlanningChips(null); presentPlanningQuestion();
}

async function generateContentPlan() {
  if (planningState.generating) return;
  planningState.generating = true; $('planning-save-state').textContent = '正在生成方案…';
  const card = addPlanningMessage('亲，正在梳理你的保险主线、泛内容候选和合集结构，马上给你第一版。', 'assistant', false);
  try {
    const response = await fetch('/api/content-plan/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agentId: state.matched ? state.profile.agentId : '', profile: state.profile, planning: planningState.context }) });
    const result = await response.json(); if (!response.ok) throw new Error(result.error || '生成失败');
    const version = result.version || planningState.version; const saved = { version, plan: result.plan, model: result.model }; if (state.matched) planningState.plans.unshift(saved); else planningState.plans = [saved]; planningState.version = version + 1;
    card.textContent = `内容规划 V${version} 已生成，正在打开方案预览。`; if (state.matched) persistPlanningMessage('assistant', `内容规划 V${version} 已生成。`); refreshContentPlanButton(); renderContentPlan(result.plan, version);
  } catch (error) { card.textContent = `生成失败：${error.message}`; }
  finally { planningState.generating = false; $('planning-save-state').textContent = state.matched ? '已保存到历史档案' : '本次会话'; }
}

async function reviseContentPlan(revision) {
  if (planningState.generating) return;
  const current = planningState.plans[0]; if (!current) return generateContentPlan();
  planningState.generating = true; $('planning-save-state').textContent = '正在调整方案…';
  const card = addPlanningMessage('收到，亲。我会保留合理部分，再按你的补充重新整理成一个可执行的新版本。', 'assistant', false);
  try {
    const response = await fetch('/api/content-plan/revise', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agentId: state.matched ? state.profile.agentId : '', profile: state.profile, planning: planningState.context, currentPlan: current.plan, revision }) });
    const result = await response.json(); if (!response.ok) throw new Error(result.error || '调整失败');
    const version = result.version || planningState.version; const saved = { version, plan: result.plan, model: result.model }; if (state.matched) planningState.plans.unshift(saved); else planningState.plans.unshift(saved); planningState.version = version + 1;
    card.textContent = `已按你的补充生成内容规划 V${version}，正在打开预览。`; if (state.matched) persistPlanningMessage('assistant', `内容规划 V${version} 已按对话调整。`); refreshContentPlanButton(); renderContentPlan(result.plan, version);
  } catch (error) { card.textContent = `调整失败：${error.message}`; }
  finally { planningState.generating = false; $('planning-save-state').textContent = state.matched ? '已保存到历史档案' : '本次会话'; }
}

function addMessage(text, kind = 'assistant', persist = true) {
  const node = document.createElement('div');
  node.className = `message ${kind}`;
  node.textContent = text;
  messages.appendChild(node);
  messages.scrollTop = messages.scrollHeight;
  if (persist && state.matched) persistMessage(kind, text);
  return node;
}

async function persistMessage(role, content) {
  try {
    await fetch('/api/message', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agentId: state.profile.agentId, role, content }) });
  } catch (_) { $('save-state').textContent = '暂未保存，请检查网络'; }
}

function setInputMode(question) {
  const input = $('chat-input');
  input.type = question?.inputMode === 'numeric' ? 'number' : 'text';
  input.inputMode = question?.inputMode === 'numeric' ? 'numeric' : 'text';
  input.step = question?.inputMode === 'numeric' ? '1' : '';
  input.min = question?.inputMode === 'numeric' ? '0' : '';
}

function setChips(question) {
  const area = $('quick-replies');
  area.innerHTML = '';
  if (!question) return;
  question.chips.forEach((chip) => {
    const button = document.createElement('button');
    button.textContent = chip;
    if (question.multiple) {
      button.classList.toggle('selected', state.multiSelection.has(chip));
      button.onclick = () => toggleMultiOption(chip);
    } else button.onclick = () => answer(chip);
    area.appendChild(button);
  });
  if (question.multiple) {
    Array.from(state.multiSelection).filter((value) => !question.chips.includes(value)).forEach((value) => {
      const selected = document.createElement('button');
      selected.className = 'selected custom-selected';
      selected.textContent = `${value} ×`;
      selected.onclick = () => toggleMultiOption(value);
      area.appendChild(selected);
    });
    const custom = document.createElement('div');
    custom.className = 'custom-multi-input';
    const customInput = document.createElement('input');
    customInput.placeholder = `补充其他${question.label}…`;
    const add = document.createElement('button');
    add.type = 'button'; add.textContent = '添加';
    const addCustom = () => {
      const value = customInput.value.trim();
      if (!value) return;
      state.multiSelection.add(value); customInput.value = ''; setChips(question);
    };
    add.onclick = addCustom;
    customInput.onkeydown = (event) => { if (event.key === 'Enter') { event.preventDefault(); addCustom(); } };
    custom.append(customInput, add); area.appendChild(custom);
    const confirm = document.createElement('button');
    confirm.className = 'primary multi-confirm'; confirm.textContent = `确认已选（${state.multiSelection.size}）`; confirm.disabled = state.multiSelection.size === 0;
    confirm.onclick = confirmMultiOption; area.appendChild(confirm);
  }
}

function toggleMultiOption(value) {
  if (state.multiSelection.has(value)) state.multiSelection.delete(value); else state.multiSelection.add(value);
  setChips(questions[state.currentQuestion]);
}

async function confirmMultiOption() {
  const question = questions[state.currentQuestion];
  const value = Array.from(state.multiSelection).join('、');
  if (!value) return;
  addMessage(value, 'user'); state.profile[question.key] = value; state.multiSelection = new Set(); state.currentQuestion += 1;
  setChips(null); renderProfile(); await persistMatchedProfile(); presentQuestion();
}

function presentQuestion() {
  const question = questions[state.currentQuestion];
  if (!question) return completeProfile();
  if (state.profile[question.key]) { state.currentQuestion += 1; return presentQuestion(); }
  $('chat-title').textContent = '通过对话补充你的资料';
  $('chat-input').placeholder = `填写${question.label}…`; setInputMode(question); state.multiSelection = new Set();
  addMessage(question.ask); setChips(question);
}

function renderProfile() {
  const keys = ['name', 'agentId', 'selfIntro', 'purpose', ...questions.map((q) => q.key), 'generationNotes'];
  const known = keys.filter((key) => state.profile[key]);
  $('completion').textContent = `${Math.round((known.length / keys.length) * 100)}%`;
  $('profile-card').innerHTML = keys.map((key) => `<div class="profile-group"><span class="profile-label">${labels[key] || key}</span><div class="profile-value ${state.profile[key] ? '' : 'profile-empty'}">${state.profile[key] || '待补充'}</div></div>`).join('');
  $('generate-button').disabled = !state.done;
}

function refreshProposalButton() {
  const button = $('view-proposal');
  if (state.proposals.length) { button.classList.remove('hidden'); button.textContent = `查看最新方案 · V${state.proposals[0].version}`; }
  else button.classList.add('hidden');
}

async function persistMatchedProfile() {
  if (!state.matched) return;
  const response = await fetch('/api/profile', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agentId: state.profile.agentId, profile: state.profile }) });
  if (response.ok) $('save-state').textContent = '已保存到历史档案';
}

function parseRevision(text) {
  const updates = {};
  const city = text.match(/(?:城市|我在)\s*(?:改为|是)?\s*(成都|上海|北京|广州|深圳|杭州|武汉|南京|苏州|重庆)/);
  if (city) updates.city = city[1];
  const target = text.match(/(?:客户画像|目标客户|服务对象|服务人群)(?:改为|是|：|:)?\s*(.+)/);
  if (target) updates.customerGroups = target[1].trim();
  const strength = text.match(/(专业靠谱|善于沟通|有温度|行动力强|耐心倾听|资源整合|善于规划)/);
  if (strength) updates.strengths = strength[1];
  const honor = text.match(/(MDRT|TOT|COT|五星会员)/i);
  if (honor) updates.honors = honor[1].toUpperCase();
  if (/(昵称|简介|学历|风格|不想突出|气质)/.test(text)) updates.generationNotes = text;
  return updates;
}

async function applyPendingUpdate(node) {
  if (!state.pendingUpdate) return;
  Object.assign(state.profile, state.pendingUpdate); state.pendingUpdate = null;
  const notice = addMessage('亲，档案已经换成这版啦。接下来重新生成方案，就能看到新效果。', 'system');
  if (node) node.replaceWith(notice);
  renderProfile(); await persistMatchedProfile();
}

function confirmRevision(updates, intro = '我读懂啦，下面这些内容准备写进档案：') {
  state.pendingUpdate = updates;
  const node = document.createElement('div'); node.className = 'message assistant';
  const title = document.createElement('strong'); title.textContent = intro;
  const detail = document.createElement('div'); detail.textContent = Object.entries(updates).map(([key, value]) => `${labels[key] || key} = ${value}`).join('；');
  const confirm = document.createElement('button'); confirm.className = 'primary confirm-update'; confirm.textContent = '就按这个改';
  const cancel = document.createElement('button'); cancel.className = 'text-button cancel-update'; cancel.textContent = '先不动';
  confirm.onclick = () => applyPendingUpdate(node);
  cancel.onclick = () => { state.pendingUpdate = null; const notice = addMessage('好，这次先不动档案。想好后再叫我，我就在这儿。', 'system'); node.replaceWith(notice); };
  node.append(title, detail, confirm, cancel); messages.appendChild(node); messages.scrollTop = messages.scrollHeight;
}

async function understandFollowUp(content) {
  const response = await fetch('/api/chat', {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ profile: state.profile, message: content }),
  });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || '暂时没有听清这句话');
  return result;
}

function isGenerateRequest(content) {
  return /(?:生成|出|做).{0,8}(?:IP\s*)?方案|方案.{0,6}(?:生成|出)|^(?:帮我|请|现在|直接|可以|重新|开始).{0,10}(?:生成|出方案)/.test(content);
}

async function answer(value) {
  const content = value.trim(); if (!content) return;
  if (state.done) {
    addMessage(content, 'user');
    const confirmsUpdate = /^(就按|确认|好的|好呀|可以|改吧|执行|更新|没问题)/.test(content);
    if (state.pendingUpdate && confirmsUpdate) {
      await applyPendingUpdate();
      if (isGenerateRequest(content)) return generateProposal();
      return;
    }
    if (isGenerateRequest(content)) return generateProposal();
    $('save-state').textContent = '正在理解你的补充…';
    try {
      const result = await understandFollowUp(content);
      if (Object.keys(result.updates || {}).length) return confirmRevision(result.updates, result.reply);
      addMessage(result.reply, 'assistant');
    } catch (error) {
      const updates = parseRevision(content);
      if (Object.keys(updates).length) return confirmRevision(updates, '我先抓到了这些重点，确认一下就写进档案：');
      addMessage('亲，这句话我还没完全拿准，不过没关系。你换个说法告诉我想改什么，我会先复述给你确认。', 'assistant');
    } finally {
      $('save-state').textContent = state.matched ? '已保存到历史档案' : '本次会话';
    }
    return;
  }
  const question = questions[state.currentQuestion];
  if (question.multiple) { state.multiSelection.add(content); $('chat-input').value = ''; setChips(question); return; }
  if (question.inputMode === 'numeric' && !/^\d+(?:\.\d+)?$/.test(content)) { addMessage('请只输入从业年限的数字，例如 9。', 'assistant'); return; }
  addMessage(content, 'user'); state.profile[question.key] = ['跳过', '不希望填写'].includes(content) ? '' : `${content}${question.suffix || ''}`;
  state.currentQuestion += 1; setChips(null); renderProfile(); await persistMatchedProfile(); presentQuestion();
}

function completeProfile() {
  state.done = true; setChips(null); setInputMode(null); $('chat-input').placeholder = '可继续补充或修改资料…';
  if (!state.hasHistory) addMessage('亲，资料已整理完成，正在自动生成你的专属 IP 方案。', 'system');
  renderProfile();
  if (!state.proposals.length && !state.autoGenerated) {
    state.autoGenerated = true;
    setTimeout(() => generateProposal(), 250);
  }
}

function startWorkspace(profile, matched, history = [], proposals = [], planningHistory = [], contentPlans = []) {
  state.matched = matched; state.profile = profile; state.currentQuestion = 0; state.done = false; state.hasHistory = history.length > 0; state.autoGenerated = false;
  state.proposals = proposals.sort((a, b) => b.version - a.version); state.version = (state.proposals[0]?.version || 0) + 1; messages.innerHTML = '';
  planningState.context = {}; planningState.currentQuestion = 0; planningState.done = false; planningState.started = false; planningState.hasHistory = planningHistory.length > 0; planningState.messages = planningHistory; planningState.plans = contentPlans.sort((a, b) => b.version - a.version); planningState.version = (planningState.plans[0]?.version || 0) + 1; planningMessages().innerHTML = '';
  if (matched) localStorage.setItem(SESSION_KEY, JSON.stringify({ name: profile.name, agentId: profile.agentId }));
  $('identity-screen').classList.add('hidden'); $('workspace').classList.remove('hidden');
  $('identity-state').textContent = matched ? `已匹配：${profile.name}（${profile.agentId}）` : '访客模式：资料仅保留本次会话';
  $('save-state').textContent = matched ? '已载入历史档案' : '本次会话';
  if (history.length) history.forEach((item) => addMessage(item.content, item.role, false));
  else addMessage(matched ? `你好，${profile.name}。你的报名资料已经带入，接下来补充生成方案需要的关键信息。` : '亲，欢迎加入友邦红人计划。我们会通过对话建立本次 IP 档案。');
  renderProfile(); refreshProposalButton(); presentQuestion(); selectTool(state.requestedTool || 'ip');
}

function makeNode(tag, className, text) { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; }
function asArray(value) { return Array.isArray(value) ? value.filter(Boolean) : []; }

function copyText(text, button) {
  navigator.clipboard?.writeText(text).then(() => { const original = button.textContent; button.textContent = '已复制'; setTimeout(() => { button.textContent = original; }, 1200); }).catch(() => { button.textContent = '请手动复制'; });
}

function addCopyBlock(parent, variant, platform) {
  const block = makeNode('section', 'bio-copy-block'); const heading = makeNode('div', 'bio-copy-heading'); const label = makeNode('div');
  label.append(makeNode('strong', '', variant.label || '简介方案'), makeNode('span', 'bio-focus', variant.focus || ''));
  const copy = makeNode('button', 'copy-button', '复制全文'); const lines = asArray(variant.lines); const text = lines.join('\n'); copy.onclick = () => copyText(text, copy);
  heading.append(label, copy); const textarea = document.createElement('textarea'); textarea.className = 'bio-textarea'; textarea.value = text; textarea.readOnly = true; textarea.rows = Math.max(4, lines.length); textarea.setAttribute('aria-label', `${platform}${variant.label || ''}简介`);
  block.append(heading, textarea); if (platform !== '小红书') block.append(makeNode('p', 'license-note', '上传前请将“000”替换为本人执业编号。')); parent.appendChild(block);
}

function createInfoCard(title, content) { const card = makeNode('section', 'proposal-card'); card.append(makeNode('h3', '', title)); if (typeof content === 'string') card.append(makeNode('p', 'proposal-copy', content)); else card.append(content); return card; }

function renderProposal(proposal, version) {
  const content = $('proposal-content'); content.innerHTML = ''; $('proposal-version').textContent = `方案 V${version}`;
  const hero = makeNode('section', 'proposal-hero'); hero.append(makeNode('p', 'eyebrow', '你的个人 IP 方案'), makeNode('h1', '', proposal.headline || '为你生成的 IP 定位'), makeNode('p', 'proposal-subheadline', proposal.subheadline || ''));
  const tags = makeNode('div', 'proposal-tags'); asArray(proposal.tags).slice(0, 3).forEach((tag) => tags.append(makeNode('span', '', tag))); hero.append(tags); content.appendChild(hero);
  const overview = makeNode('div', 'proposal-grid'); overview.append(createInfoCard(proposal.clientPortrait?.title || '🎯 目标客户画像', proposal.clientPortrait?.text || ''));
  const advantages = makeNode('div', 'compact-list advantage-list'); asArray(proposal.advantages).slice(0, 4).forEach((item) => { const row = makeNode('div', 'compact-row'); row.append(makeNode('span', 'item-emoji', item.emoji || '✨')); const words = makeNode('div'); words.append(makeNode('strong', '', item.title || ''), makeNode('span', '', item.text || '')); row.append(words); advantages.append(row); }); overview.append(createInfoCard('✨ 你的优势', advantages)); content.appendChild(overview);
  const nicknameList = makeNode('div', 'nickname-list'); asArray(proposal.nicknameOptions).slice(0, 5).forEach((item) => { const row = makeNode('div', 'nickname-option'); const words = makeNode('div'); words.append(makeNode('strong', '', item.name || ''), makeNode('span', 'nickname-angle', item.angle || ''), makeNode('p', '', item.reason || '')); const copy = makeNode('button', 'copy-button', '复制昵称'); copy.onclick = () => copyText(item.name || '', copy); row.append(words, copy); nicknameList.append(row); }); content.appendChild(createInfoCard('✍️ 推荐昵称', nicknameList));
  const bios = makeNode('section', 'proposal-card bio-section'); bios.append(makeNode('h3', '', '📱 可直接复制的平台简介'));
  const platformGrid = makeNode('div', 'platform-grid'); const xhs = makeNode('div', 'platform-column'); xhs.append(makeNode('h4', '', '小红书简介 · 两套选择')); asArray(proposal.bios?.xiaohongshu).slice(0, 2).forEach((item) => addCopyBlock(xhs, item, '小红书'));
  const video = makeNode('div', 'platform-column'); video.append(makeNode('h4', '', '视频号 / 抖音简介 · 两套选择')); asArray(proposal.bios?.videoDouyin).slice(0, 2).forEach((item) => addCopyBlock(video, item, '视频号 / 抖音')); platformGrid.append(xhs, video); bios.append(platformGrid); content.appendChild(bios);
  const compliance = makeNode('section', 'compliance-card'); compliance.append(makeNode('h3', '', '🛡️ 简介修改合规提示'), makeNode('p', 'proposal-copy', '复制后如需自行调整，请先对照以下提示。小红书简介的限制尤其严格。'));
  const complianceGrid = makeNode('div', 'compliance-grid'); const allowed = makeNode('div', 'compliance-column allowed'); allowed.append(makeNode('h4', '', '可以表达')); COMPLIANCE_TIPS.allowed.forEach((item) => { const row = makeNode('div', 'compliance-row'); row.append(makeNode('span', '', item.emoji), makeNode('p', '', `${item.title}：${item.text}`)); allowed.append(row); });
  const avoid = makeNode('div', 'compliance-column avoid'); avoid.append(makeNode('h4', '', '避免写入')); COMPLIANCE_TIPS.avoid.forEach((item) => { const row = makeNode('div', 'compliance-row'); row.append(makeNode('span', '', item.emoji), makeNode('p', '', `${item.title}：${item.text}`)); avoid.append(row); }); complianceGrid.append(allowed, avoid); compliance.append(complianceGrid); content.appendChild(compliance);
  const reminders = makeNode('section', 'platform-reminders'); reminders.append(makeNode('h3', '', '📌 平台修改机会提醒')); asArray(proposal.platformReminders).forEach((line) => reminders.append(makeNode('p', '', line))); content.appendChild(reminders);
  $('proposal-screen').classList.remove('hidden'); document.body.classList.add('proposal-open');
}

function contentPlanCard(title, body, className = '') {
  const card = makeNode('section', `proposal-card ${className}`.trim());
  card.append(makeNode('h3', '', title));
  if (typeof body === 'string') card.append(makeNode('p', 'proposal-copy', body)); else card.append(body);
  return card;
}

function renderContentPlan(plan, version) {
  const content = $('content-plan-content'); content.innerHTML = ''; $('content-plan-version').textContent = `内容规划 V${version}`;
  const hero = makeNode('section', 'proposal-hero content-plan-hero');
  hero.append(makeNode('p', 'eyebrow', '你的账号内容规划'), makeNode('h1', '', plan.finalPositioning?.label || '保险 + 1 内容结构'), makeNode('p', 'proposal-subheadline', plan.summary || '围绕明确的保险主线与一个泛内容方向，持续建立信任。'));
  const tags = makeNode('div', 'proposal-tags'); [plan.primaryGoal || '内容规划', plan.insuranceLine?.title || '保险主线', '固定 1 + 1'].forEach((tag) => tags.append(makeNode('span', '', tag))); hero.append(tags); content.appendChild(hero);

  const core = makeNode('div', 'content-plan-core');
  core.append(contentPlanCard('① 保险主线', plan.insuranceLine?.reason || '从你的 IP、目标人群和服务优势中确定保险内容的核心。'));
  core.append(contentPlanCard('② 最终账号定位', plan.finalPositioning?.explanation || '每个账号只保留一个最终泛内容主线。'));
  content.appendChild(core);

  const candidates = makeNode('div', 'planning-candidate-list');
  asArray(plan.candidateDirections).slice(0, 3).forEach((item) => {
    const card = makeNode('article', `planning-candidate ${item.recommend ? 'recommended' : ''}`);
    const heading = makeNode('div', 'planning-candidate-heading'); heading.append(makeNode('strong', '', item.direction || '候选方向')); if (item.recommend) heading.append(makeNode('span', '', '推荐')); card.append(heading);
    [['人群匹配', item.audienceFit], ['持续输出', item.sustainable], ['利他价值', item.benefit]].forEach(([label, value]) => { const row = makeNode('p', ''); row.append(makeNode('b', '', `${label}：`), document.createTextNode(value || '待结合实际经历验证')); card.append(row); });
    candidates.append(card);
  });
  content.appendChild(contentPlanCard('🧭 保险 + N 候选筛选', candidates));

  const collectionList = makeNode('div', 'collection-list');
  asArray(plan.collections).slice(0, 5).forEach((item, index) => {
    const collection = makeNode('article', 'collection-card'); collection.append(makeNode('span', 'collection-number', `合集 ${index + 1}`), makeNode('h4', '', item.name || '内容合集'));
    collection.append(makeNode('p', '', `解决的问题：${item.audienceQuestion || '围绕目标受众的真实问题展开'}`), makeNode('p', '', `内容边界：${item.contentBoundary || '不偏离账号定位'}`));
    const topics = makeNode('div', 'topic-pills'); asArray(item.topics).slice(0, 4).forEach((topic) => topics.append(makeNode('span', '', topic))); collection.append(topics); collectionList.append(collection);
  });
  content.appendChild(contentPlanCard('🗂️ 账号作品合集与首批选题', collectionList));

  const firstMonth = makeNode('div', 'compact-list');
  [['内容比例', plan.firstMonth?.ratio], ['发布节奏', plan.firstMonth?.rhythm]].forEach(([title, text]) => { const row = makeNode('div', 'compact-row'); row.append(makeNode('span', 'item-emoji', title === '内容比例' ? '⚖️' : '🗓️')); const words = makeNode('div'); words.append(makeNode('strong', '', title), makeNode('span', '', text || '结合账号实际情况安排')); row.append(words); firstMonth.append(row); });
  const weekly = makeNode('div', 'weekly-plan'); asArray(plan.firstMonth?.weeklyPlan).slice(0, 4).forEach((item, index) => weekly.append(makeNode('p', '', `第 ${index + 1} 周 · ${item}`))); firstMonth.append(weekly);
  content.appendChild(contentPlanCard('📅 首月执行节奏', firstMonth));

  const avoid = makeNode('div', 'avoid-direction-list'); asArray(plan.avoidDirections).slice(0, 3).forEach((item) => { const row = makeNode('div', 'compact-row'); row.append(makeNode('span', 'item-emoji', '⛔')); const words = makeNode('div'); words.append(makeNode('strong', '', item.direction || '不建议混入'), makeNode('span', '', item.reason || '避免内容偏离已确定的人群与定位。')); row.append(words); avoid.append(row); }); content.appendChild(contentPlanCard('⚠️ 不建议混入的方向', avoid));
  const reminder = makeNode('section', 'platform-reminders focus-reminder'); reminder.append(makeNode('h3', '', '📌 内容聚焦提醒'), makeNode('p', '', plan.focusReminder || '内容不要太杂、太随意地混发。账号像朋友圈，平台就难判断该把你推给谁，长期容易让流量画像失焦。')); content.appendChild(reminder);
  $('content-plan-screen').classList.remove('hidden'); document.body.classList.add('proposal-open');
}

$('lookup-form').addEventListener('submit', async (event) => { event.preventDefault(); const name = $('name-input').value.trim(); const agentId = $('agent-id-input').value.trim(); const response = await fetch(`/api/lookup?name=${encodeURIComponent(name)}&agentId=${encodeURIComponent(agentId)}`); const result = await response.json(); if (result.matched) return startWorkspace(result.profile, true, result.history || [], result.proposals || [], result.planningHistory || [], result.contentPlans || []); startWorkspace({ name, agentId }, false); });
$('guest-start').onclick = () => startWorkspace({}, false);
document.querySelectorAll('.identity-tool').forEach((button) => { button.onclick = () => chooseToolBeforeLogin(button.dataset.tool); });
document.querySelectorAll('.tool-tab').forEach((button) => { button.onclick = () => selectTool(button.dataset.tool); });
$('switch-account').onclick = () => { localStorage.removeItem(SESSION_KEY); window.location.reload(); };
$('view-proposal').onclick = () => { if (state.proposals[0]) renderProposal(state.proposals[0].proposal, state.proposals[0].version); };
$('proposal-close').onclick = () => { $('proposal-screen').classList.add('hidden'); document.body.classList.remove('proposal-open'); };
$('content-plan-close').onclick = () => { $('content-plan-screen').classList.add('hidden'); document.body.classList.remove('proposal-open'); };
$('view-content-plan').onclick = () => { if (planningState.plans[0]) renderContentPlan(planningState.plans[0].plan, planningState.plans[0].version); };
$('chat-form').addEventListener('submit', (event) => { event.preventDefault(); answer($('chat-input').value); $('chat-input').value = ''; });
$('planning-form').addEventListener('submit', (event) => { event.preventDefault(); planningAnswer($('planning-input').value); $('planning-input').value = ''; });
async function generateProposal() {
  if (state.generating) return;
  state.generating = true;
  const button = $('generate-button'); button.disabled = true; button.textContent = '正在生成…'; const card = addMessage('亲，正在生成你的专属 IP 方案，稍等我一下。', 'assistant', false);
  try {
    const response = await fetch('/api/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agentId: state.matched ? state.profile.agentId : '', profile: state.profile }) });
    const result = await response.json(); if (!response.ok) throw new Error(result.error || '生成失败');
    const version = result.version || state.version; const saved = { version, proposal: result.proposal, model: result.model }; if (state.matched) state.proposals.unshift(saved); state.version = version + 1;
    card.textContent = `方案 V${version} 已生成，正在打开预览页。`; if (state.matched) persistMessage('assistant', `IP 方案 V${version} 已生成。`); refreshProposalButton(); renderProposal(result.proposal, version);
  } catch (error) { card.textContent = `生成失败：${error.message}`; }
  finally { state.generating = false; button.disabled = false; button.textContent = '重新生成专属 IP 方案'; }
}
$('generate-button').onclick = generateProposal;

async function resumeSavedSession() {
  let saved; try { saved = JSON.parse(localStorage.getItem(SESSION_KEY) || 'null'); } catch (_) { localStorage.removeItem(SESSION_KEY); }
  if (!saved?.name || !saved?.agentId) return;
  try { const response = await fetch(`/api/lookup?name=${encodeURIComponent(saved.name)}&agentId=${encodeURIComponent(saved.agentId)}`); const result = await response.json(); if (result.matched) startWorkspace(result.profile, true, result.history || [], result.proposals || [], result.planningHistory || [], result.contentPlans || []); else localStorage.removeItem(SESSION_KEY); }
  catch (_) { $('save-state').textContent = '无法连接资料服务'; }
}

resumeSavedSession();
