// IP 人设首次进入体验：功能欢迎卡 -> 已有资料确认 -> 第一个缺失问题。
// 此文件在 app.js 之后加载，只覆盖首次进入相关交互，不改变其他工具逻辑。

function addIpWelcomeCard() {
  const card = document.createElement('div');
  card.className = 'creative-welcome-card ip-welcome-card';
  card.innerHTML = `
    <p class="creative-welcome-eyebrow">✨ IP 人设 · 从真实的你开始</p>
    <h3>把“你是谁”，变成别人记得住的账号</h3>
    <p class="creative-welcome-intro">我会从你的真实经历、客户方向和个人优势里，找到最适合长期经营的 IP 主线。</p>
    <div class="creative-welcome-list">
      <div><span>🧭</span><div><strong>人设定位</strong><p>找到你最值得被记住的那一面</p></div></div>
      <div><span>✍️</span><div><strong>直接可用</strong><p>生成昵称、账号简介和表达方向</p></div></div>
      <div><span>🛡️</span><div><strong>合规护航</strong><p>自动避开常见平台和行业风险</p></div></div>
    </div>
    <p class="creative-welcome-hint">接下来回答几个简单问题，我们一起把第一版 IP 搭出来。</p>`;
  messages.appendChild(card);
  messages.scrollTop = messages.scrollHeight;
  return card;
}

function ipKnownSummary(profile) {
  const candidates = [
    ['所在城市', profile.city],
    ['服务人群', profile.customerGroups],
    ['从业时间', profile.insuranceYears],
    ['荣誉', profile.honors],
    ['学历', profile.education],
    ['优势', profile.strengths],
  ].filter(([, value]) => value && value !== '跳过' && value !== '不希望填写');
  return candidates.slice(0, 4);
}

function addMatchedIpSummary(profile) {
  const known = ipKnownSummary(profile);
  const node = document.createElement('div');
  node.className = 'message assistant ip-known-summary';
  const title = document.createElement('strong');
  title.textContent = `${profile.name || '你的'}部分资料我已经带进来了。`;
  node.appendChild(title);
  if (known.length) {
    const tags = document.createElement('div');
    tags.className = 'ip-known-tags';
    known.forEach(([label, value]) => {
      const tag = document.createElement('span');
      tag.textContent = `${label}：${value}`;
      tags.appendChild(tag);
    });
    node.appendChild(tags);
  }
  const note = document.createElement('p');
  note.textContent = '已有的信息不用重复填，我们只补还缺的部分。';
  node.appendChild(note);
  messages.appendChild(node);
  messages.scrollTop = messages.scrollHeight;
  return node;
}

const originalIpAnswer = answer;
answer = async function onboardingAwareAnswer(value) {
  const content = String(value || '').trim();
  if (!content) return;
  if (!state.done && ['跳过', '不希望填写'].includes(content)) {
    const question = questions[state.currentQuestion];
    if (!question) return;
    addMessage(content, 'user');
    // 明确跳过也视为已回答，避免下次进入时重复追问。
    state.profile[question.key] = content;
    state.currentQuestion += 1;
    setChips(null);
    renderProfile();
    await persistMatchedProfile();
    presentQuestion();
    return;
  }
  return originalIpAnswer(value);
};

startWorkspace = function onboardingStartWorkspace(profile, matched, history = [], proposals = [], planningHistory = [], contentPlans = [], creativeHistory = []) {
  state.matched = matched; state.profile = profile; state.currentQuestion = 0; state.done = false; state.hasHistory = history.length > 0; state.autoGenerated = false;
  state.proposals = proposals.sort((a, b) => b.version - a.version); state.version = (state.proposals[0]?.version || 0) + 1; messages.innerHTML = '';
  planningState.context = {}; planningState.currentQuestion = 0; planningState.done = false; planningState.started = false; planningState.multiSelection = new Set(); planningState.suggestions = []; planningState.hasHistory = planningHistory.length > 0; planningState.messages = planningHistory; planningState.plans = contentPlans.sort((a, b) => b.version - a.version); planningState.version = (planningState.plans[0]?.version || 0) + 1; planningMessages().innerHTML = '';
  ['script', 'xhs'].forEach((tool) => { creativeState[tool].started = false; creativeState[tool].source = ''; creativeState[tool].generating = false; creativeState[tool].pendingRisks = false; creativeState[tool].pendingRevision = ''; creativeState[tool].messages = creativeHistory.filter((item) => item.tool === tool); creativeMessages(tool).innerHTML = ''; });
  if (matched) localStorage.setItem(SESSION_KEY, JSON.stringify({ name: profile.name, agentId: profile.agentId }));
  $('identity-screen').classList.add('hidden'); $('workspace').classList.remove('hidden');
  $('identity-state').textContent = matched ? `已匹配：${profile.name}（${profile.agentId}）` : '访客模式：资料仅保留本次会话';
  $('save-state').textContent = matched ? '已载入历史档案' : '本次会话';

  const firstIpVisit = history.length === 0 && proposals.length === 0;
  if (history.length) {
    history.forEach((item) => restoreIpPlanHistoryItem(item));
  } else if (firstIpVisit) {
    addIpWelcomeCard();
    if (matched) addMatchedIpSummary(profile);
    else addMessage('接下来我会问你几个很简单的问题。按真实情况回答就好，我会边聊边把你的 IP 轮廓拼出来。', 'assistant', false);
  } else if (matched) {
    addMessage(`欢迎回来，${profile.name}。已载入你的 IP 档案和已有方案。`, 'assistant', false);
  }

  renderProfile(); refreshProposalButton(); presentQuestion();
  const defaultTool = !state.requestedTool && state.proposals.length && planningState.plans.length ? 'script' : (state.requestedTool || 'ip');
  selectTool(defaultTool);
};
